server:
  port: 8080
eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud.gateway:
    discovery:
      locator:
        enabled: true
        lowerCaseServiceId: true
    routes:
      - id: sms-verification
        uri: lb://demo/v1/sms-verification
        predicates:
          - Path=/v1/sms-verification
      - id: baeldung__route
        uri: http://baeldung.com
        predicates:
          - Path=/baeldung/**