server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eurekaa: false
    instance:
      preferIpAddress: true

spring:
  application:
    name: gateway
  cloud.gateway:
    routes:
      - id: sms-verification
        uri: lb://demo
        predicates:
          - Path=/demo/**
      - id: baeldung__route
        uri: http://baeldung.com
        predicates:
          - Path=/baeldung/**
        filters:
          - StripPrefix=1